// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.0
// source: poker_hand_history_v1.proto

package handpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Simulation-only binary contract stored in PostgreSQL BYTEA. Monetary values
// use millionths of one currency unit so the wire format never depends on
// floating-point rounding.
type HandHistoryV1 struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	HandId           string                 `protobuf:"bytes,1,opt,name=hand_id,json=handId,proto3" json:"hand_id,omitempty"`
	GameType         string                 `protobuf:"bytes,2,opt,name=game_type,json=gameType,proto3" json:"game_type,omitempty"`
	TableId          string                 `protobuf:"bytes,3,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	PlayedAtUnixMs   int64                  `protobuf:"varint,4,opt,name=played_at_unix_ms,json=playedAtUnixMs,proto3" json:"played_at_unix_ms,omitempty"`
	DatasetSplit     string                 `protobuf:"bytes,5,opt,name=dataset_split,json=datasetSplit,proto3" json:"dataset_split,omitempty"`
	Generator        string                 `protobuf:"bytes,6,opt,name=generator,proto3" json:"generator,omitempty"`
	SmallBlindMicros int64                  `protobuf:"varint,7,opt,name=small_blind_micros,json=smallBlindMicros,proto3" json:"small_blind_micros,omitempty"`
	BigBlindMicros   int64                  `protobuf:"varint,8,opt,name=big_blind_micros,json=bigBlindMicros,proto3" json:"big_blind_micros,omitempty"`
	NumPlayers       int32                  `protobuf:"varint,9,opt,name=num_players,json=numPlayers,proto3" json:"num_players,omitempty"`
	PotSizeMicros    int64                  `protobuf:"varint,10,opt,name=pot_size_micros,json=potSizeMicros,proto3" json:"pot_size_micros,omitempty"`
	Board            []string               `protobuf:"bytes,11,rep,name=board,proto3" json:"board,omitempty"`
	Actions          []*HandActionV1        `protobuf:"bytes,12,rep,name=actions,proto3" json:"actions,omitempty"`
	Players          []*HandPlayerV1        `protobuf:"bytes,13,rep,name=players,proto3" json:"players,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HandHistoryV1) Reset() {
	*x = HandHistoryV1{}
	mi := &file_poker_hand_history_v1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandHistoryV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandHistoryV1) ProtoMessage() {}

func (x *HandHistoryV1) ProtoReflect() protoreflect.Message {
	mi := &file_poker_hand_history_v1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandHistoryV1.ProtoReflect.Descriptor instead.
func (*HandHistoryV1) Descriptor() ([]byte, []int) {
	return file_poker_hand_history_v1_proto_rawDescGZIP(), []int{0}
}

func (x *HandHistoryV1) GetHandId() string {
	if x != nil {
		return x.HandId
	}
	return ""
}

func (x *HandHistoryV1) GetGameType() string {
	if x != nil {
		return x.GameType
	}
	return ""
}

func (x *HandHistoryV1) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

func (x *HandHistoryV1) GetPlayedAtUnixMs() int64 {
	if x != nil {
		return x.PlayedAtUnixMs
	}
	return 0
}

func (x *HandHistoryV1) GetDatasetSplit() string {
	if x != nil {
		return x.DatasetSplit
	}
	return ""
}

func (x *HandHistoryV1) GetGenerator() string {
	if x != nil {
		return x.Generator
	}
	return ""
}

func (x *HandHistoryV1) GetSmallBlindMicros() int64 {
	if x != nil {
		return x.SmallBlindMicros
	}
	return 0
}

func (x *HandHistoryV1) GetBigBlindMicros() int64 {
	if x != nil {
		return x.BigBlindMicros
	}
	return 0
}

func (x *HandHistoryV1) GetNumPlayers() int32 {
	if x != nil {
		return x.NumPlayers
	}
	return 0
}

func (x *HandHistoryV1) GetPotSizeMicros() int64 {
	if x != nil {
		return x.PotSizeMicros
	}
	return 0
}

func (x *HandHistoryV1) GetBoard() []string {
	if x != nil {
		return x.Board
	}
	return nil
}

func (x *HandHistoryV1) GetActions() []*HandActionV1 {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *HandHistoryV1) GetPlayers() []*HandPlayerV1 {
	if x != nil {
		return x.Players
	}
	return nil
}

type HandActionV1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SequenceNo    uint32                 `protobuf:"varint,1,opt,name=sequence_no,json=sequenceNo,proto3" json:"sequence_no,omitempty"`
	PlayerId      string                 `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Street        string                 `protobuf:"bytes,3,opt,name=street,proto3" json:"street,omitempty"`
	ActionType    string                 `protobuf:"bytes,4,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`
	AmountMicros  int64                  `protobuf:"varint,5,opt,name=amount_micros,json=amountMicros,proto3" json:"amount_micros,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandActionV1) Reset() {
	*x = HandActionV1{}
	mi := &file_poker_hand_history_v1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandActionV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandActionV1) ProtoMessage() {}

func (x *HandActionV1) ProtoReflect() protoreflect.Message {
	mi := &file_poker_hand_history_v1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandActionV1.ProtoReflect.Descriptor instead.
func (*HandActionV1) Descriptor() ([]byte, []int) {
	return file_poker_hand_history_v1_proto_rawDescGZIP(), []int{1}
}

func (x *HandActionV1) GetSequenceNo() uint32 {
	if x != nil {
		return x.SequenceNo
	}
	return 0
}

func (x *HandActionV1) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *HandActionV1) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *HandActionV1) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

func (x *HandActionV1) GetAmountMicros() int64 {
	if x != nil {
		return x.AmountMicros
	}
	return 0
}

type HandPlayerV1 struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PlayerId         string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Position         string                 `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	StackStartMicros int64                  `protobuf:"varint,4,opt,name=stack_start_micros,json=stackStartMicros,proto3" json:"stack_start_micros,omitempty"`
	HoleCards        []string               `protobuf:"bytes,5,rep,name=hole_cards,json=holeCards,proto3" json:"hole_cards,omitempty"`
	WonAmountMicros  int64                  `protobuf:"varint,6,opt,name=won_amount_micros,json=wonAmountMicros,proto3" json:"won_amount_micros,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HandPlayerV1) Reset() {
	*x = HandPlayerV1{}
	mi := &file_poker_hand_history_v1_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandPlayerV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandPlayerV1) ProtoMessage() {}

func (x *HandPlayerV1) ProtoReflect() protoreflect.Message {
	mi := &file_poker_hand_history_v1_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandPlayerV1.ProtoReflect.Descriptor instead.
func (*HandPlayerV1) Descriptor() ([]byte, []int) {
	return file_poker_hand_history_v1_proto_rawDescGZIP(), []int{2}
}

func (x *HandPlayerV1) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *HandPlayerV1) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HandPlayerV1) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *HandPlayerV1) GetStackStartMicros() int64 {
	if x != nil {
		return x.StackStartMicros
	}
	return 0
}

func (x *HandPlayerV1) GetHoleCards() []string {
	if x != nil {
		return x.HoleCards
	}
	return nil
}

func (x *HandPlayerV1) GetWonAmountMicros() int64 {
	if x != nil {
		return x.WonAmountMicros
	}
	return 0
}

var File_poker_hand_history_v1_proto protoreflect.FileDescriptor

const file_poker_hand_history_v1_proto_rawDesc = "" +
	"\n" +
	"\x1bpoker_hand_history_v1.proto\x12\x13poker.simulation.v1\"\xff\x03\n" +
	"\rHandHistoryV1\x12\x17\n" +
	"\ahand_id\x18\x01 \x01(\tR\x06handId\x12\x1b\n" +
	"\tgame_type\x18\x02 \x01(\tR\bgameType\x12\x19\n" +
	"\btable_id\x18\x03 \x01(\tR\atableId\x12)\n" +
	"\x11played_at_unix_ms\x18\x04 \x01(\x03R\x0eplayedAtUnixMs\x12#\n" +
	"\rdataset_split\x18\x05 \x01(\tR\fdatasetSplit\x12\x1c\n" +
	"\tgenerator\x18\x06 \x01(\tR\tgenerator\x12,\n" +
	"\x12small_blind_micros\x18\a \x01(\x03R\x10smallBlindMicros\x12(\n" +
	"\x10big_blind_micros\x18\b \x01(\x03R\x0ebigBlindMicros\x12\x1f\n" +
	"\vnum_players\x18\t \x01(\x05R\n" +
	"numPlayers\x12&\n" +
	"\x0fpot_size_micros\x18\n" +
	" \x01(\x03R\rpotSizeMicros\x12\x14\n" +
	"\x05board\x18\v \x03(\tR\x05board\x12;\n" +
	"\aactions\x18\f \x03(\v2!.poker.simulation.v1.HandActionV1R\aactions\x12;\n" +
	"\aplayers\x18\r \x03(\v2!.poker.simulation.v1.HandPlayerV1R\aplayers\"\xaa\x01\n" +
	"\fHandActionV1\x12\x1f\n" +
	"\vsequence_no\x18\x01 \x01(\rR\n" +
	"sequenceNo\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\x12\x16\n" +
	"\x06street\x18\x03 \x01(\tR\x06street\x12\x1f\n" +
	"\vaction_type\x18\x04 \x01(\tR\n" +
	"actionType\x12#\n" +
	"\ramount_micros\x18\x05 \x01(\x03R\famountMicros\"\xd4\x01\n" +
	"\fHandPlayerV1\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bposition\x18\x03 \x01(\tR\bposition\x12,\n" +
	"\x12stack_start_micros\x18\x04 \x01(\x03R\x10stackStartMicros\x12\x1d\n" +
	"\n" +
	"hole_cards\x18\x05 \x03(\tR\tholeCards\x12*\n" +
	"\x11won_amount_micros\x18\x06 \x01(\x03R\x0fwonAmountMicrosBZZXgithub.com/ai-campions/snowflake-poker-ml-pipeline/services/go/internal/cdc/proto;handpbb\x06proto3"

var (
	file_poker_hand_history_v1_proto_rawDescOnce sync.Once
	file_poker_hand_history_v1_proto_rawDescData []byte
)

func file_poker_hand_history_v1_proto_rawDescGZIP() []byte {
	file_poker_hand_history_v1_proto_rawDescOnce.Do(func() {
		file_poker_hand_history_v1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_poker_hand_history_v1_proto_rawDesc), len(file_poker_hand_history_v1_proto_rawDesc)))
	})
	return file_poker_hand_history_v1_proto_rawDescData
}

var file_poker_hand_history_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_poker_hand_history_v1_proto_goTypes = []any{
	(*HandHistoryV1)(nil), // 0: poker.simulation.v1.HandHistoryV1
	(*HandActionV1)(nil),  // 1: poker.simulation.v1.HandActionV1
	(*HandPlayerV1)(nil),  // 2: poker.simulation.v1.HandPlayerV1
}
var file_poker_hand_history_v1_proto_depIdxs = []int32{
	1, // 0: poker.simulation.v1.HandHistoryV1.actions:type_name -> poker.simulation.v1.HandActionV1
	2, // 1: poker.simulation.v1.HandHistoryV1.players:type_name -> poker.simulation.v1.HandPlayerV1
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_poker_hand_history_v1_proto_init() }
func file_poker_hand_history_v1_proto_init() {
	if File_poker_hand_history_v1_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_poker_hand_history_v1_proto_rawDesc), len(file_poker_hand_history_v1_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_poker_hand_history_v1_proto_goTypes,
		DependencyIndexes: file_poker_hand_history_v1_proto_depIdxs,
		MessageInfos:      file_poker_hand_history_v1_proto_msgTypes,
	}.Build()
	File_poker_hand_history_v1_proto = out.File
	file_poker_hand_history_v1_proto_goTypes = nil
	file_poker_hand_history_v1_proto_depIdxs = nil
}
