# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: poker_hand_history_v1.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'poker_hand_history_v1.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bpoker_hand_history_v1.proto\x12\x13poker.simulation.v1\"\xe5\x02\n\rHandHistoryV1\x12\x0f\n\x07hand_id\x18\x01 \x01(\t\x12\x11\n\tgame_type\x18\x02 \x01(\t\x12\x10\n\x08table_id\x18\x03 \x01(\t\x12\x19\n\x11played_at_unix_ms\x18\x04 \x01(\x03\x12\x15\n\rdataset_split\x18\x05 \x01(\t\x12\x11\n\tgenerator\x18\x06 \x01(\t\x12\x1a\n\x12small_blind_micros\x18\x07 \x01(\x03\x12\x18\n\x10\x62ig_blind_micros\x18\x08 \x01(\x03\x12\x13\n\x0bnum_players\x18\t \x01(\x05\x12\x17\n\x0fpot_size_micros\x18\n \x01(\x03\x12\r\n\x05\x62oard\x18\x0b \x03(\t\x12\x32\n\x07\x61\x63tions\x18\x0c \x03(\x0b\x32!.poker.simulation.v1.HandActionV1\x12\x32\n\x07players\x18\r \x03(\x0b\x32!.poker.simulation.v1.HandPlayerV1\"r\n\x0cHandActionV1\x12\x13\n\x0bsequence_no\x18\x01 \x01(\r\x12\x11\n\tplayer_id\x18\x02 \x01(\t\x12\x0e\n\x06street\x18\x03 \x01(\t\x12\x13\n\x0b\x61\x63tion_type\x18\x04 \x01(\t\x12\x15\n\ramount_micros\x18\x05 \x01(\x03\"\x8c\x01\n\x0cHandPlayerV1\x12\x11\n\tplayer_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08position\x18\x03 \x01(\t\x12\x1a\n\x12stack_start_micros\x18\x04 \x01(\x03\x12\x12\n\nhole_cards\x18\x05 \x03(\t\x12\x19\n\x11won_amount_micros\x18\x06 \x01(\x03\x42ZZXgithub.com/ai-campions/snowflake-poker-ml-pipeline/services/go/internal/cdc/proto;handpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'poker_hand_history_v1_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZXgithub.com/ai-campions/snowflake-poker-ml-pipeline/services/go/internal/cdc/proto;handpb'
  _globals['_HANDHISTORYV1']._serialized_start=53
  _globals['_HANDHISTORYV1']._serialized_end=410
  _globals['_HANDACTIONV1']._serialized_start=412
  _globals['_HANDACTIONV1']._serialized_end=526
  _globals['_HANDPLAYERV1']._serialized_start=529
  _globals['_HANDPLAYERV1']._serialized_end=669
# @@protoc_insertion_point(module_scope)
