CREATE TABLE IF NOT EXISTS FEATURES (
    hand_id              STRING NOT NULL,
    player_id            STRING NOT NULL,
    -- Card features
    rank1                FLOAT,
    rank2                FLOAT,
    gap                  FLOAT,
    is_suited            FLOAT,
    is_pair              FLOAT,
    hand_strength        FLOAT,
    high_card            FLOAT,
    low_card             FLOAT,
    -- Position/stack
    position_idx         FLOAT,
    stack_bb             FLOAT,
    is_blind             FLOAT,
    is_late              FLOAT,
    -- Per-street action counts (4 streets x bet/raise/call/check/fold counts + invested)
    preflop_bets         FLOAT,
    preflop_raises       FLOAT,
    preflop_calls        FLOAT,
    preflop_checks       FLOAT,
    preflop_folds        FLOAT,
    preflop_invested     FLOAT,
    preflop_aggression   FLOAT,
    flop_bets            FLOAT,
    flop_raises          FLOAT,
    flop_calls           FLOAT,
    flop_checks          FLOAT,
    flop_folds           FLOAT,
    flop_invested        FLOAT,
    flop_aggression      FLOAT,
    turn_bets            FLOAT,
    turn_raises          FLOAT,
    turn_calls           FLOAT,
    turn_checks          FLOAT,
    turn_folds           FLOAT,
    turn_invested        FLOAT,
    turn_aggression      FLOAT,
    river_bets           FLOAT,
    river_raises         FLOAT,
    river_calls          FLOAT,
    river_checks         FLOAT,
    river_folds          FLOAT,
    river_invested       FLOAT,
    river_aggression     FLOAT,
    -- Aggregates
    total_invested       FLOAT,
    total_invest_ratio   FLOAT,
    total_aggression     FLOAT,
    saw_flop             FLOAT,
    saw_turn             FLOAT,
    saw_river            FLOAT,
    saw_showdown         FLOAT,
    -- Hand-level
    num_raisers_preflop  FLOAT,
    num_saw_flop         FLOAT,
    num_players_hand     FLOAT,
    pot_to_stack_ratio   FLOAT,
    is_suspicious        FLOAT,
    computed_at          TIMESTAMP_TZ,
    PRIMARY KEY (hand_id, player_id)
);

CREATE TABLE IF NOT EXISTS RULE_FLAGS (
    hand_id                  STRING  NOT NULL,
    player_id                STRING  NOT NULL,
    flag_eligible            BOOLEAN NOT NULL,
    flag_pre_mw              BOOLEAN NOT NULL,
    flag_pre_ofold_commit    BOOLEAN NOT NULL,
    flag_post_ofold_commit   BOOLEAN NOT NULL,
    flag_high_invest_fold    BOOLEAN NOT NULL,
    flag_position_anomaly    BOOLEAN NOT NULL,
    rule_score               FLOAT   NOT NULL,
    triggered_rules          ARRAY,
    PRIMARY KEY (hand_id, player_id)
);
