-- Account-scoped objects. This pool starts suspended and consumes no compute
-- until a service or job is deployed.
USE ROLE ACCOUNTADMIN;

CREATE COMPUTE POOL IF NOT EXISTS POKER_ML_CPU_POOL
  MIN_NODES = 1
  MAX_NODES = 1
  INSTANCE_FAMILY = CPU_X64_S
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  AUTO_SUSPEND_SECS = 300;

GRANT USAGE, MONITOR ON COMPUTE POOL POKER_ML_CPU_POOL TO ROLE SYSADMIN;
GRANT BIND SERVICE ENDPOINT ON ACCOUNT TO ROLE SYSADMIN;

-- Schema-scoped deployment objects.
USE ROLE SYSADMIN;
USE DATABASE POKER_ML_DEMO;

CREATE SCHEMA IF NOT EXISTS SPCS;
USE SCHEMA SPCS;

CREATE IMAGE REPOSITORY IF NOT EXISTS POKER_ML_REPO;

CREATE STAGE IF NOT EXISTS SERVICE_SPECS
  DIRECTORY = (ENABLE = TRUE)
  ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');

CREATE STAGE IF NOT EXISTS MODEL_ARTIFACTS
  DIRECTORY = (ENABLE = TRUE)
  ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');

CREATE STAGE IF NOT EXISTS ML_JOB_PAYLOADS
  DIRECTORY = (ENABLE = TRUE)
  ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');
